version: '3.8'

services:
  embeddings:
    build: .
    restart: always
    container_name: embeddings
    command: sh run.sh
    environment:
      - ENV=local
    ports:
      - 5004:5000
    env_file:
      - local.env
    networks:
      - dev-network
    volumes:
      - ./model_weights:/app/model_weights 
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            capabilities:
              - gpu
              - utility # nvidia-smi
              - compute # CUDA
              - video   

networks:
  dev-network:  # Define the network explicitly
    driver: bridge
    name: dev-network